### ISSUE TITLE
Lenovo Legion 5 Pro Gen 7 AMD keyboard not recognized

### ISSUE THREAD

**Issue by GustavoCab2** [4JX/L5P-Keyboard-RGB#100]
When I open the app is says, "A valid keyboard model was not found. It may be due to a hardware error."

Lenovo Legion 5 Pro Gen 7 AMD
Model: 16ARH7H
Type Model: 82RG001MUS
Win 11

**Comment by henrich-micko** [comment]
I have same problem with Lenovo Legion 5 15ACH6H Fedora

**Comment by GustavoCab2** [comment]
@4JX Lenovo Vantage does recognize it but it only shows 3 profiles which is high light, low light and off and it does do anything.

<img width="711" alt="Screenshot_20230104_081023" src="https://user-images.githubusercontent.com/121449189/210673712-e4484ea8-8b78-4af8-866d-3aacaa4394cc.png">

**Comment by 4JX** [comment]
You have a white backlight model which is not supported by this software.

**Comment by GustavoCab2** [comment]
@4JX I'm sure I bought the RGB version. I think it says that because my motherboard doesn't identify the type of keyboard I have.

**Comment by 4JX** [comment]
If neither Vantage nor the program can properly detect it the only option is to contact Lenovo's support team.

**Comment by GustavoCab2** [comment]
I already did but they didn't resolve the problem but thank you for trying to help!
