### ISSUE TITLE
sudo: ./legion-kb-rgb-linux: command not found

### ISSUE THREAD

**Issue by formidabilus** [4JX/L5P-Keyboard-RGB#102]
After downloading the v0.18.0 linux zip, when I try to double click the executable after extract, it can't find any program to open this kind of file and if I use the CLI to open it `sudo ./legion-kb-rgb-linux` in the file of extraction, it gives me `command not found`.

 I use Fedora37, am I doing something wrong?

**Comment by 4JX** [comment]
Are you sure the filename is `legion-kb-rgb-linux`? The zip file that holds the release is named like that, but the executable inside is called `legion-kb-rgb`.

**Comment by formidabilus** [comment]
my bad, I meant: 

`sudo ./legion-kb-rgb
sudo: ./legion-kb-rgb: command not found
`

**Comment by 4JX** [comment]
Can you run `ls` in the folder you are trying to run the command in?

**Comment by formidabilus** [comment]
here is the result:

`❯ ls
legion-kb-rgb
❯ ls -la
total 12384
drwxr-xr-x. 1 vnm_rzv vnm_rzv       26 feb  6 03:53 .
drwxr-xr-x. 1 vnm_rzv vnm_rzv     2834 feb  8 03:36 ..
-rw-rw-r--. 1 vnm_rzv vnm_rzv 12677680 nov  5 00:44 legion-kb-rgb`

**Comment by formidabilus** [comment]
I have managed to open it, it didn't have permission to execute, I just saw it. Sorry for the disturbance.
