### ISSUE TITLE
Temperature not working (Arch)

### ISSUE THREAD

**Issue by dewyi** [4JX/L5P-Keyboard-RGB#104]
Vanilla arch with DWM installed.
Linux 6.2.1-arch1-1 x86_64
Version 0.19.0-dev
82SA Lenovo Ideapad Gaming 3 16IAH7
intel 12th gen cpu, nvidia 3060m

temperature gradient not working and can't find logs

**Comment by yaweetsta** [comment]
Hey can you help me get in the software by any chance my user is yaweet#4563 on discord i can screenshare you and show you my problem!

**Comment by 4JX** [comment]
Hello, can you try again with https://github.com/4JX/L5P-Keyboard-RGB/actions/runs/4747218092?

Aditionally, do you have the folders `/sys/class/hwmon` and `/sys/class/thermal` in your system?

**Comment by dewyi** [comment]
> Hello, can you try again with https://github.com/4JX/L5P-Keyboard-RGB/actions/runs/4747218092?
> 
> Aditionally, do you have the folders `/sys/class/hwmon` and `/sys/class/thermal` in your system?

When I "sudo ./legion-kb-rgb"
./legion-kb-rgb: error while loading shared libraries: libgstvideo-1.0.so.0: cannot open shared object file: No such file or directory

**Comment by 4JX** [comment]
Try installing the equivalent of `gst_all_1.gstreamer gst_all_1.gst-plugins-base` in your system

**Comment by yaweetsta** [comment]
> Try installing the equivalent of `gst_all_1.gstreamer gst_all_1.gst-plugins-base` in your system

Im clicking on the thing i cant install it?

**Comment by 4JX** [comment]
You should search for those dependencies in the package repo for Arch/AUR and install them as the program requires them
