### ISSUE TITLE
Color is not saved

### ISSUE THREAD

**Issue by Nosnahc** [4JX/L5P-Keyboard-RGB#106]
HI!
The color returns to a default value after each reboot.
I don't know if that's normal.
Maybe I'm doing something wrong?

**Comment by 4JX** [comment]
> HI! The color returns to a default value after each reboot. I don't know if that's normal. Maybe I'm doing something wrong?

The program does not start itself at boot automatically, you need to manually set it up yourself.

**Comment by Nosnahc** [comment]
Thanks!
