### ISSUE TITLE
Legion RBG

### ISSUE THREAD

**Issue by yaweetsta** [4JX/L5P-Keyboard-RGB#107]
Hey when i open the software it says 
![image](https://user-images.githubusercontent.com/128108927/225790943-a56ccbcb-2762-4802-aa48-6bdce39d0203.png)
If you know how to solve this please add my discord its yaweet#4563 i tried downloading linux and all that but i still dont know how to fix it.

**Comment by Nosnahc** [comment]
Have you tried to run it as administrator ?

**Comment by yaweetsta** [comment]
> Have you tried to run it as administrator ?

Yes

**Comment by 4JX** [comment]
Can you try https://github.com/4JX/L5P-Keyboard-RGB/actions/runs/4746596729?

What is your laptop's model number? Does Vantage work with the keyboard?

**Comment by yaweetsta** [comment]
> Can you try https://github.com/4JX/L5P-Keyboard-RGB/actions/runs/4746596729?
> 
> What is your laptop's model number? Does Vantage work with the keyboard?

IdeaPad Gaming 3 15ACH6 i have the white backlight keyboard, If it dosent work I just need a color changer no effects or anything its just so simple

**Comment by 4JX** [comment]
> > Can you try https://github.com/4JX/L5P-Keyboard-RGB/actions/runs/4746596729?
> > What is your laptop's model number? Does Vantage work with the keyboard?
> 
> IdeaPad Gaming 3 15ACH6 i have the white backlight keyboard, If it dosent work I just need a color changer no effects or anything its just so simple

White backlight models are not supported by this app. It is physically impossible to make them output any other color than white as they only contain white LEDs.

**Comment by yaweetsta** [comment]
> > > Can you try https://github.com/4JX/L5P-Keyboard-RGB/actions/runs/4746596729?
> > > What is your laptop's model number? Does Vantage work with the keyboard?
> > 
> > 
> > IdeaPad Gaming 3 15ACH6 i have the white backlight keyboard, If it dosent work I just need a color changer no effects or anything its just so simple
> 
> White backlight models are not supported by this app. It is physically impossible to make them output any other color than white as they only contain white LEDs.

Oh alr mbon the other response i thought it was mines you can delete it
