### ISSUE TITLE
Keyboard not recognized

### ISSUE THREAD

**Issue by MalcolmYork** [4JX/L5P-Keyboard-RGB#110]
Hello,

I just tried this software and got an error message. 
Find bellow the backtrace.

 RUST_BACKTRACE=full ./legion-kb-rgb set --effect Static
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Could not create keyboard manager
├╴ app/src/effects/mod.rs:81:14
│
├─▶ There was an error getting a valid keyboard
│   ├╴ app/src/effects/mod.rs:78:14
│   ├╴ Ensure that you have a supported model and that the application has access to it.
│   ╰╴ On Linux, see https://github.com/4JX/L5P-Keyboard-RGB#usage
│
╰─▶ Error: Couldn't find device
    ├╴ app/src/effects/mod.rs:77:14
    ╰╴ backtrace (1)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

backtrace no. 1
   0: error_stack::report::Report<C>::from_frame
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/error-stack-0.2.4/src/report.rs:244:30
   1: error_stack::report::Report<C>::new
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/error-stack-0.2.4/src/report.rs:220:9
   2: error_stack::context::<impl core::convert::From<C> for error_stack::report::Report<C>>::from
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/error-stack-0.2.4/src/context.rs:83:9
   3: <core::result::Result<T,E> as error_stack::result::IntoReport>::into_report
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/error-stack-0.2.4/src/result.rs:210:31
   4: legion_kb_rgb::effects::EffectManager::new
             at /home/runner/work/L5P-Keyboard-RGB/L5P-Keyboard-RGB/app/src/effects/mod.rs:76:24
   5: legion_kb_rgb::main
             at /home/runner/work/L5P-Keyboard-RGB/L5P-Keyboard-RGB/app/src/main.rs:59:38
   6: core::ops::function::FnOnce::call_once
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
   7: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:121:18
   8: std::rt::lang_start::{{closure}}
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/rt.rs:166:18
   9: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:286:13
  10: std::panicking::try::do_call
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:483:40
  11: std::panicking::try
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:447:19
  12: std::panic::catch_unwind
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panic.rs:137:14
  13: std::rt::lang_start_internal::{{closure}}
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/rt.rs:148:48
  14: std::panicking::try::do_call
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:483:40
  15: std::panicking::try
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:447:19
  16: std::panic::catch_unwind
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panic.rs:137:14
  17: std::rt::lang_start_internal
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/rt.rs:148:20
  18: std::rt::lang_start
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/rt.rs:165:17
  19: main
  20: __libc_start_call_main
  21: __libc_start_main@@GLIBC_2.34
  22: _start
Location: app/src/main.rs:59

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 9 frames hidden ⋮                               
  10: core::result::Result<T,E>::unwrap::h37141fe6f4cfa72a
      at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1113
  11: legion_kb_rgb::main::hae6f51ca41df665d
      at /home/runner/work/L5P-Keyboard-RGB/L5P-Keyboard-RGB/app/src/main.rs:59
  12: core::ops::function::FnOnce::call_once::h714e4eb5c1ba4044
      at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251
                                ⋮ 16 frames hidden ⋮

**Comment by 4JX** [comment]
What's your laptop model? If on Linux, did you add the udev rules?

**Comment by MalcolmYork** [comment]
Hi,

I am on Fedora 38. I did not add any udev rules yet.
The laptop model is Legion 7 16ACHG6.

------- Original Message -------

**Comment by 4JX** [comment]
Legion 7 models are not supported, consider https://openrgb.org/ instead
