### ISSUE TITLE
[Question] What is the new format for auto load a profile on boot?

### ISSUE THREAD

**Issue by Rodrxx** [4JX/L5P-Keyboard-RGB#112]
As the title says, default.json no longer auto loads my profiles into the program, so i got welcome'd by a black keyboard (no lightning effects), it used to work like a charm before, but once i upgraded to v19, i cant get a profile to autoload when my pc boots up

**Comment by 4JX** [comment]
See the release notes

> Users relying on the undocumented but often mentioned default.json file method should switch to this instead.

Instead of using a file, specify your profile via the command line and pass the `--gui` flag if you want to also start that on boot

**Comment by Rodrxx** [comment]
Understandable, still i managed to load it through command line, but there is something, if i want to launch the GUI im unable to do so, when i load the profile in CMD, the command window get stuck and i cannot input anything more, and there is no application showing in the tray for quick access or configure in the GUI, so i have to close the command line, therefore closing the rgb app from memory so i have to launch it again.

Im a little of a noob in terms of command line, now i have to create a .bat file with the correct lines of code so it can run my chosen profile, and put the .bat file in the startup folder, i think that is the way.

**Comment by 4JX** [comment]
For the GUI part do `./programname set -e <effect> <other options> --gui` with that `--gui` flag added as well

**Comment by Rodrxx** [comment]
I managed to do it, thanks, as for other question, how can i save 2 profiles in one .json file?, since i wont launch the GUI at boot, i want to change between 2 profiles i made in the GUI via Win+AltGr

**Comment by 4JX** [comment]
You cannot save multiple profiles to an exported json file, but the entire list of profiles you create should still be stored in a `settings.json` file. You may need to use an [unreleased version](https://github.com/4JX/L5P-Keyboard-RGB/actions/runs/5072283559) for `Win+AltGr` functionality for v19

**Comment by Rodrxx** [comment]
> stored in a `settings.json` file.

I dont have such settings.json file in the directory i run rgb, it should be generated automatically or i have to manually save into a "settings.json" file?

Also, im using the lastest dev version, the same you reference as the unreleased version

**Comment by 4JX** [comment]
It gets generated on exit (pressing the exit button, not killing the app or just when shutting off your computer) as of now, should probably update it more often

**Comment by Rodrxx** [comment]
Thanks for the reply, now it is working as intended, set every profile in the GUI, then pressed "exit", a ´settings.json´ appeared, now everytime i open the rgb.exe it loads by default the ´settings.json´ file, with that in mind, now in the shortcut i created that is in the startup folder, i wrote on target ´(exe path) -g -w´, now everytime my pc boots up, it loads up the ´settings.json´ file created earlier by default, and the GUI doesnt appear so this is the best state of the app for me, thanks for your effort.
