### ISSUE TITLE
Ambience light effect works slow Mint linux

### ISSUE THREAD

**Issue by Edward0058** [4JX/L5P-Keyboard-RGB#116]

**Comment by Edward0058** [comment]
The lights are 3 sec late

**Comment by 4JX** [comment]
Cannot reproduce, works fine for me. What version are you using? Have you set the FPS (if on v0.19)?

**Comment by 4JX** [comment]
Can you test with https://github.com/4JX/L5P-Keyboard-RGB/releases/tag/v0.19.0?

**Comment by Edward0058** [comment]
used it on mint with latest kernel

**Comment by Edward0058** [comment]
i switched distro since then it works fine on ubuntu when u set fpas to 10
