### ISSUE TITLE
Ambient light ubuntu 

### ISSUE THREAD

**Issue by Edward0058** [4JX/L5P-Keyboard-RGB#118]
Terminal view :
No subcommands found, starting in GUI mode. To view the possible subcommands type "rgb --help".
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Failed to obtain screen capture." }
Location: app/src/effects/ambient.rs:25

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by 4JX** [comment]
What display server/DE are you using? And what Ubuntu version?

**Comment by Edward0058** [comment]
Ubuntu 22.04.2 LTS, ,gnome. noveau driver

**Comment by Edward0058** [comment]
it was working until i switched the display driver from nvidia
