### ISSUE TITLE
Legion 5 Pro 16ARX8

### ISSUE THREAD

**Issue by FranciscoRibeiro03** [4JX/L5P-Keyboard-RGB#119]
I have a Legion 5 Pro Gen 8 with AMD processor (16ARX8) and the app doesn't work for me. Tried on Windows 11 and Arch Linux. 

I am able to switch through 3 profiles + off through Vantage 
![image](https://github.com/4JX/L5P-Keyboard-RGB/assets/15705566/632f8b73-f581-44e7-a8b4-a25c0705431a)

Is there anything I can do to help debug this issue? Thank you in advance!

EDIT: Screenshot of the error that happens both on Windows and on Linux, along with console output
![image](https://github.com/4JX/L5P-Keyboard-RGB/assets/15705566/745c2ea5-dd13-48ff-bb69-073cc7a198bf)

**Comment by 4JX** [comment]
Hey can you test the version in https://github.com/4JX/L5P-Keyboard-RGB/actions/runs/5555683399

**Comment by OrderlyUnicode** [comment]
Not the OP, but after applying the fix from #124 and building this, it detected the keyboard probably and with the exception of a few of the animations listed not seeming to do anything, worked perfectly.

**Comment by 4JX** [comment]
> Not the OP, but after applying the fix from #124 and building this, it detected the keyboard probably and with the exception of a few of the animations listed not seeming to do anything, worked perfectly.

What's your laptop model?

**Comment by FranciscoRibeiro03** [comment]
> Hey can you test the version in https://github.com/4JX/L5P-Keyboard-RGB/actions/runs/5555683399

Sorry for the delayed answer, I was not home when you sent me that and I just remembered to test this app now because of the notifications 😅 
With that version (tested on Windows) everything worked except for the Temperature effect. I don't even know how to describe it, it looks like it just "crashes" the app without actually closing it. I can still use the app and change to other effects, but as soon as I switch to the Temperature effect, the lights just turn off and have no effect at all. 
I don't know what this effect should actually do tho, so I don't know how to actually test it.

**Comment by OrderlyUnicode** [comment]
Same model, Legion Pro 5 16ARX8, but I'm on Arch

**Comment by 4JX** [comment]
> it looks like it just "crashes" the app without actually closing it

That's expected, it should transition between green and red depending on the CPU's temps but windows refuses to cooperate. I removed the restriction of using it there in case it magically starts working one day.

> Same model, Legion Pro 5 16ARX8, but I'm on Arch
Did you use your own compiled version or the one mentioned here? Did it include the patch in #120?

**Comment by OrderlyUnicode** [comment]
Both? I downloaded the source with the patch and #120 and ran into the problems building it that prompted #124 , so I was trying that one with the main branch to make sure the problem wasn't related to the patch before doing the same thing with the #120 branch
