### ISSUE TITLE
Legion RGB profile running at start up

### ISSUE THREAD

**Issue by Phexoe** [4JX/L5P-Keyboard-RGB#121]
As of right now, I have found no way to have my preset effect running at boot, I have to manually open the app and set it myself otherwise it won't be applied. I'm running legion toolkit and I have disabled backlight support from the app. Is there a way to fix this ?

Thanks

**Comment by 4JX** [comment]
There's no built in functionality to automatically run it at boot, if you wish to do that you'll have to manually add it to some place like the startup folder or the task scheduler and configure it as needed with the CLI options

**Comment by Rodrxx** [comment]
Define a folder to have the .exe and the settings.json (all the profiles you created in the gui) stored, then create a shortcut of the .exe and place it on the startup folder (Win+R then write shell:startup, place it there), then go to the shortcut properties and in target just write at the end "-g -w", now the rgb should start everytime at boot with the profiles you have created

**Comment by Db2203** [comment]
> Define a folder to have the .exe and the settings.json (all the profiles you created in the gui) stored, then create a shortcut of the .exe and place it on the startup folder (Win+R then write shell:startup, place it there), then go to the shortcut properties and in target just write at the end "-g -w", now the rgb should start everytime at boot with the profiles you have created

If i do this, can i still switch between profiles using win+ R Alt?
