### ISSUE TITLE
Task tray show and quit unresponsive version 0.19

### ISSUE THREAD

**Issue by cn293** [4JX/L5P-Keyboard-RGB#122]
L5P-Keyboard-RGB version 0.19
Linux Mint 21.2 (kernel version 5.15.0-78)
Lenovo Legion 5 15IAH7H

Not sure I'm doing anything wrong as version 0.18 works but 0.19 doesn't:

ISSUE:
After legion-kb-rgb is started up, the GUI is displayed and an icon added to the system tray.  When the window is closed the process continues to run in the background. This is expected. Clicking the system tray icon 'Show' option does not bring up the GUI for the running process. Clicking 'Quit' does nothing either. The only way to close the process is to kill it via the terminal. 

This occurs whether started via the terminal, or started by clicking the file, or started via a .desktop entry. udev rules were added as per the install instructions. The package was downloaded as a pre-compiled binary from the 'release page

WORKAROUND:
Downgraded to version 0.18. Swapping the legion-kb-rgb version 0.19 file out with the version 0.18 file works. On window close the process continues to run in the background, 'Show' brings up the GUI, and 'Quit' closes the process.

Version 0.18 is quite nice though :)

**Comment by 4JX** [comment]
Is anything printed out to the console error message wise when starting the app or interacting with the tray icon? Does it otherwise function as normal?

**Comment by cn293** [comment]
Thanks for the response. No, nothing except the "No sub commands found, starting in GUI mode..." message. CTL-C kills the running task. The app seems to function as normal but I didn't test much. It's just the unresponsive tray icon that is a problem. Right-clicking it displays the show-quit menu but clicking either option doesn't do anything. Not sure this isn't a package dependency issue, though this system is up to date.

![screenshot-legion-kb-after-closing-clicking-show-quit](https://github.com/4JX/L5P-Keyboard-RGB/assets/87828880/cca1e0f5-60e9-4345-83c5-60f6bf8f0025)
![screenshot-legion-kb-after-ctl-c](https://github.com/4JX/L5P-Keyboard-RGB/assets/87828880/11a816bc-c118-419e-8967-1a5750060189)
![screenshot-legion-kb-app-started](https://github.com/4JX/L5P-Keyboard-RGB/assets/87828880/e63d8680-04a0-43b7-b5fe-6fae44c68787)

**Comment by 4JX** [comment]
Note to self for this: Maybe changing to https://github.com/tauri-apps/tray-icon can help relieve some pain/also try the gtk-dependant (non forked) version of the current crate.

**Comment by Jalopy-Tech** [comment]
I have the same problem.

Kubuntu 23.04 (kernel version 6.2.0-27)
Lenovo LOQ 16 16IRH8

**Comment by 4JX** [comment]
Hello, apologies for the long wait. This should now be fixed via https://github.com/4JX/L5P-Keyboard-RGB/commit/74ae10bf62011d856b58008905904331162841b2. Can one of you test if this is the case via the builds [here](https://github.com/4JX/L5P-Keyboard-RGB/actions/runs/6448583075)? (Debug builds thus they might be slower than usual)

**Comment by 4JX** [comment]
Fixed in [0.19.3](https://github.com/4JX/L5P-Keyboard-RGB/releases/tag/v0.19.3)
