### ISSUE TITLE
Colours are washed out in AmbientLight mode

### ISSUE THREAD

**Issue by NaiveInvestigator** [4JX/L5P-Keyboard-RGB#126]
Usually when i watch any movie or have anything on screen, i notice that my keyboard light is mostly just white or slightly coloured, which is kinda boring

Could we have an option where the colours picked from the screen are boosted to 100% or the colours are made more to have more contrast, way brighter and colourful so that the keyboard is not always white anymore.

Hope you consider this feature request!

edit: basically make the colors more saturated, at the time I couldn't remember the word lol

**Comment by 4JX** [comment]
This is something that comes up to my mind every now and then. Its the result of needing to squash an entire screen into essentially 4 pixels which become really washed out since there's a bit of every color in there. Should be able to more easily add a control for this with the new ui

**Comment by 4JX** [comment]
Hey there, can you try https://github.com/4JX/L5P-Keyboard-RGB/actions/runs/6450244050 and see how that goes? Make sure to either backup your current `config.json` or add a `saturation_boost` entry into any saved profiles that have the `AmbientLight` effect (ie.  `"effect": {"AmbientLight": {"fps": 0, "saturation_boost": 0.0}},`)

**Comment by NaiveInvestigator** [comment]
Yes! it seems to be working as expected. Works really great!!

As an aside, it would be awesome too if the colours would crossfade to another color, so that change doesnt feel too jarring. I didnt notice it as much before as the colours were mostly white, eh that is a minor inconvenience.

**Comment by 4JX** [comment]
> As an aside, it would be awesome too if the colours would crossfade to another color

I guess that _could_ be done while the FPS is set to something low but I believe it would be better to leave it as an instant change since you'll most likely be using this at higher FPS

**Comment by 4JX** [comment]
Proper (full performance) release [0.19.3](https://github.com/4JX/L5P-Keyboard-RGB/releases/tag/v0.19.3)
