### ISSUE TITLE
Help to support for Legion Pro 5 16ARX8 needed?

### ISSUE THREAD

**Issue by jschneider** [4JX/L5P-Keyboard-RGB#132]
Hi mate, 

I have bought a new Legion 5 with these values:

```
Manufacturer: LENOVO
Product Name: 82WM
Version: Legion Pro 5 16ARX8

Legion Pro 5 16ARX8
```

```
lsusb | grep 048d
Bus 005 Device 005: ID 048d:c985 Integrated Technology Express, Inc. ITE Device(8295)
Bus 005 Device 004: ID 048d:c103 Integrated Technology Express, Inc. ITE Device(8910)
```

I get the message "There was an error getting a valid keyboard" which seems to be expected.
Anything I can do to help supporting this notebook?

**Comment by 4JX** [comment]
Hey there, support for that model was added in #120, though I have not made a formal release yet (will do in a bit and then just add bugfixing for other stuff at a latter date).

In the meantime you should be able to download it from https://github.com/4JX/L5P-Keyboard-RGB/actions/runs/5837593685

**Comment by jschneider** [comment]
Thanks!
I downloaded the file from here:
https://github.com/4JX/L5P-Keyboard-RGB/suites/14306258478/artifacts/812609617

Unziped the file.
md5sums:
21e3999a914c5e56e7fb8238e279ec16  legion-kb-rgb
99177c4617baa8961ccdea02a4f547ca  legion-kb-rgb-linux.zip

I executed the file and got these outputs:

list:
```
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Could not create keyboard manager
├╴at app/src/effects/mod.rs:81:14
│
├─▶ There was an error getting a valid keyboard
│   ├╴at app/src/effects/mod.rs:78:14
│   ├╴Ensure that you have a supported model and that the application has access to it.
│   ╰╴On Linux, see https://github.com/4JX/L5P-Keyboard-RGB#usage
│
╰─▶ HidError: hidapi error: hid_error is not implemented yet
    ╰╴at app/src/effects/mod.rs:77:14
Location: app/src/main.rs:57
```

```
/legion-kb-rgb --version                                                                        20:22:52
Legion Keyboard Control 0.19.0
```

Maybe I somehow got the wrong version?

**Comment by 4JX** [comment]
Assuming you are on Linux you need to run the program with `sudo` or add the rules outlined in https://github.com/4JX/L5P-Keyboard-RGB#usage

**Comment by quicquid** [comment]
I was also just playing with it - I've just extended KNOWN_DEVICE_INFOS by   ```(0x048d, 0xc985, 0xff89, 0x00cc),``` but then obviously the udev rule must match as well: add ```SUBSYSTEM=="usb", ATTR{idVendor}=="048d", ATTR{idProduct}=="c985", MODE="0666"``` into the rules file too.

**Comment by jschneider** [comment]
Thanks! Forgot about the permission issue :-). 
Works fine now, thanks!
