### ISSUE TITLE
Legion 7 (AMD) support

### ISSUE THREAD

**Issue by jorisvandijk** [4JX/L5P-Keyboard-RGB#136]
Hello,
I would like to request support for the Legion 7. I own one and wouldn't mind helping make this happen if I can.

Thanks!

**Comment by 4JX** [comment]
Legion 7's won't be supported as they operate in an entirely different manner to the much simpler 4 zone one. You may wish to use [OpenRGB](https://gitlab.com/CalcProgrammer1/OpenRGB) instead.
