### ISSUE TITLE
Not working on Lenovo LOQ 15IRH8

### ISSUE THREAD

**Issue by AlteredState101** [4JX/L5P-Keyboard-RGB#137]
Would like to request support for the new LOQ 15IRH8. It has the same keyboard from the other legion models, so I'm guessing it would be an easy fix. Please try to work on it :)

**Comment by 4JX** [comment]
Are you on linux? If so can you run `lsusb | grep 048d` and post what comes out?

If not I'll get a testing program set up.

**Comment by 4JX** [comment]
>  Anything else I can do to help see if there's a way to make it work?

No just need to find time on my end to write a small test script.

Missed addressing https://github.com/4JX/L5P-Keyboard-RGB/discussions/127, which although it is for the `16IRH8` it should work for this one too (difference seems to only be the screen). Feel free to build from source in the meantime by forking the repo and adding the ID mentioned there (and triggering a compile run) or following [this](https://github.com/4JX/L5P-Keyboard-RGB/tree/a5c7b1e968d53d716c443c8041f9b786648d42d8#building-from-source)

**Comment by 4JX** [comment]
Can you try the windows download from https://github.com/4JX/L5P-Keyboard-RGB/actions/runs/6382546895 ?

**Comment by AlteredState101** [comment]
> Can you try the windows download from https://github.com/4JX/L5P-Keyboard-RGB/actions/runs/6382546895 ?

Hey man it's working beautifully!
Thank you so much for your work and effort.
