### ISSUE TITLE
Version 0.19.2: No tray icon, no warning pop-up when one of its service is already running, and can't minimize upon windows startup

### ISSUE THREAD

**Issue by Decoysan** [4JX/L5P-Keyboard-RGB#140]
Hello, I really love what you are doing with your app, but there are a few problems with the recent releases.

In the 0.19.2 and 0.19.1 versions, the tray icon does not appear anymore. The 0.19.0 still has the tray icon but it and the previous versions. But I'd prefer using the 0.19.2 because how it can easily save my last used effect upon exit and apply it upon launch.

And I also notice that the warning pop-up when one of its service is already running is also missing in the 0.19.2. I don't know if it's related to the no tray icon problem.

I also can't set the program to minimize upon Windows startup even after setting the shortcut in the startup directory to Minimized.

I'm using the Legion 5 Pro 2021 on Windows 11 latest build.

I hope you'll look into these problems. Cheers!

**Comment by 4JX** [comment]
Tray icon is known and fixed but I want confirmation that it is the case from someone else (see https://github.com/4JX/L5P-Keyboard-RGB/issues/122#issuecomment-1752092698).

Detection for whether the program was already running worked so far for me, will have a look into that.

If you want to start the program minimized/without a window pass the `-g` (start the **G**UI) and `-w` (hide the **w**indow) flags.

**Comment by Decoysan** [comment]
Thanks for replying. The test build in your link fixed the icon problem.
And now I can start the program without a window. Hurray!
But the program detection still doesn't work. With the test build, it doesn't warn me when I open the program again while the previous one is still running, and it opens, making the led flicker. Some weird thing is that while the 0.9.12 detection feature doesn't work, having duplicate programs opened doesn't make the led flicker.

**Comment by 4JX** [comment]
Can you test https://github.com/4JX/L5P-Keyboard-RGB/actions/runs/6507754521?  Should fix the detection issues. (As in the comment perform the changes to your `profile.json` so that it doesn't get wiped out)

**Comment by Decoysan** [comment]
The detection issue is fixed in that version. Thank you!

**Comment by 4JX** [comment]
Fixed in [0.19.3](https://github.com/4JX/L5P-Keyboard-RGB/releases/tag/v0.19.3)
