### ISSUE TITLE
not working on Legion 5 15IMH05H

### ISSUE THREAD

**Issue by 7FrostBites** [4JX/L5P-Keyboard-RGB#143]
![image](https://github.com/4JX/L5P-Keyboard-RGB/assets/149132631/2da6fb33-82a0-41d9-9aff-b606aa5de311)

**Comment by Labtec343** [comment]
Have the same issue model 16ITH6

**Comment by 4JX** [comment]
@7FrostBites @Labtec343 Are either of you on Linux by any chance? If not, does vantage detect your keyboard? Can you switch between custom presets or just a few "built-in" ones? And as a sanity check, you're sure you don't have a white backlight only keyboard?

The `15IMH05H` should be supported since #18, and the `16ITH6` seems to be a 2022 model which should be supported as well.

**Comment by 7FrostBites** [comment]
my vantage haven't been detecting my keyboard for a while now which was the reason I was using this application cause it detected it then it just stipped

**Comment by 4JX** [comment]
> my vantage haven't been detecting my keyboard for a while now which was the reason I was using this application cause it detected it then it just stopped

Did it stop _after_ an update or just out of the blue? If the former does reverting back to a version you knew worked help?

**Comment by 7FrostBites** [comment]
no it was out of the blue

**Comment by 4JX** [comment]
Sounds like your keyboard is faulty then. That's not something I can control.

Will wait for Labtec343's answer before closing this.

**Comment by 7FrostBites** [comment]
would you know if that would be a software or a hardware problem cause it used to work before this window pop up

**Comment by 4JX** [comment]
> my keyboard just doesnt type

Not precisely hardware but firmware or similar, though you're better off asking a technician about that.

**Comment by 7FrostBites** [comment]
okay thank you for your help

**Comment by Labtec343** [comment]
> @7FrostBites @Labtec343 Are either of you on Linux by any chance? If not, does vantage detect your keyboard? Can you switch between custom presets or just a few "built-in" ones? And as a sanity check, you're sure you don't have a white backlight only keyboard?
> 
> The `15IMH05H` should be supported since #18, and the `16ITH6` seems to be a 2022 model which should be supported as well.

No, I am on windows, I don't know if there is a way to look if the vantage detects but i'm pretty sure yes, all my Fn Keys works except the Fn + space that is the one who controls keyboard lights,  yes of course is a rgb keyboard the preset that has is a color wave form and yes the model is 2021-2022

**Comment by 4JX** [comment]
> I don't know if there is a way to look if the vantage detects but i'm pretty sure yes

If vantage detects it there should be an option to control them through there
![](https://forums.lenovo.com/uploads/topic/202111/1637616017575.png?aid=272765)

**Comment by Labtec343** [comment]
So, no this window doesn`t appears to me.

**Comment by 4JX** [comment]
Have you ever been able to control your keyboard through vantage in the time you've had the laptop?

**Comment by Labtec343** [comment]
Yes, just like 1 or 2 times when i bought the laptop, I´m not sure but I remember that this happens when I update Bios firmware like 1 or 2 years ago.

**Comment by 4JX** [comment]
Then that is a firmware problem as well and outside of what I can help with. You can try downgrading (not recommended since updates fix security vulnerabilities) or upgrading your BIOS version again to try to make it work or reinstalling the lenovo drivers. But you ought to talk to a technician/lenovo support about it.
