### ISSUE TITLE
Legion Slim 7 Gen 7

### ISSUE THREAD

**Issue by eode** [4JX/L5P-Keyboard-RGB#144]
Any chance for support of Legion Slim 7 Gen 7?  Released 2022, the USB vendor/dev are 048d:c977.

I added just the vendor/device to the array in lib.rs, but that doesn't seem to be enough -- the keyboard freezes up/stops responding altogether when I use `legion-kb-rgb --list` or run the gui.  The GUI itself doesn't freeze, though, and a reboot fixes the issue.

Let me know if I can help.

**Comment by 4JX** [comment]
Hello, the `7` model variants wont be supported by this program as they use a completely different protocol and it is not a device I have at hand to test with. You can consider using [OpenRGB](https://openrgb.org/) instead.

**Comment by eode** [comment]
Thanks.
