### ISSUE TITLE
Please add NixOS flake guide

### ISSUE THREAD

**Issue by BehradJi** [4JX/L5P-Keyboard-RGB#145]
Hi, thank you for your project, I can see that you include `flake.nix` file in your repo, could you please add NixOS instruction for how to install it using NixOS flakes?
I already included your repo in my flake `inputs` but I don't know what module to import to my flake.
This is my `flake.nix`:

```Nix
{
  description = "Behrad Nix Config";

  inputs = {

    nixpkgs.url = "github:NixOS/nixpkgs/nixos-23.11";

    home-manager = {
      url = "github:nix-community/home-manager/release-23.11";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    nixvim = {
      url = "github:nix-community/nixvim/nixos-23.11";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    nix-index-database = {
      url = "github:Mic92/nix-index-database";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    legion-keyboard = {
      url = "github:4JX/L5P-Keyboard-RGB";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = {self, nixpkgs, ... }@inputs: {
    nixosConfigurations = {
      "Legion" = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";

        modules = [
          ./system/configuration.nix
          inputs.nixvim.nixosModules.nixvim
          inputs.home-manager.nixosModules.home-manager
          inputs.nix-index-database.nixosModules.nix-index
          {
            home-manager = {
              useGlobalPkgs = true;
              useUserPackages = true;
              backupFileExtension = "hmbak";
              users.behrad.imports= [
                ./home
              ];
            };
          }
        ];
      };
    };
  };
}

```

**Comment by 4JX** [comment]
> I already included your repo in my flake inputs but I don't know what module to import to my flake.

The flake exposes no modules but rather two [`packages`](https://github.com/4JX/L5P-Keyboard-RGB/blob/225cc168c807ad12ae6723b7e6890fdad679f3a9/flake.nix#L188-L189), of which you probably want `wrapped`. 

And then you can just access the program to pass into your preferred install section as [this](https://github.com/4JX/nixos-config/blob/bde8cea5f1420e25fa61051f625629ab11a60b2c/hosts/laptop/ncfg.nix#L5)

**Comment by BehradJi** [comment]
Thank you! Now I have to find a way for making my `inputs` accessible in my `configuration.nix` file, because right now I can't use `{input , ...}:{ . . . }` in `configuration.nix` .

**Comment by 4JX** [comment]
Define `inputs` (or your preferred name), it being the attrset of inputs provided by the flake which is then passed to `outputs` (`inputs@{ self, nixpkgs, home-manager, ... }`) or just via `self.inputs`. Then add that to `specialArgs` in the `nixosSystem` function.

My version is slightly abstracted for convenience purposes but it should be easy enough to follow:
https://github.com/4JX/nixos-config/blob/b3eed993fb8b931f7e155f30449509ade4385ae4/hosts/default.nix#L26-L29
