### ISSUE TITLE
Lenovo legion 5 pro (2022) (ACH6H) no longer works with software. Keyboard not found error. 

### ISSUE THREAD

**Issue by CactusRaven** [4JX/L5P-Keyboard-RGB#147]
Worked fine up until 27th, no idea if a software/windows update broke it. Referenced in a prior (now closed) issue thread. I cannot stand the light fest anymore. When i attempt to launch application it gives a keyboard not found error and then pops up this window 

The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: ←[1mFailed to save file←[22m
├╴at ←[3mapp\src\util.rs:29:43←[23m
│
╰─▶ ←[1mAccess is denied. (os error 5)←[22m
    ╰╴at ←[3mapp\src\util.rs:29:43←[23m
Location: app\src\gui\mod.rs:319

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Press Enter to continue...

I have no idea what i could do to fix issue. Lenovo vantage does not work, legion toolkit does not work. i am not a techy person, I'm practically computer illiterate. but my eyes cant take the wave of constantly changing hues anymore.

No idea if I'm doing this correct

**Comment by 4JX** [comment]
>Lenovo vantage does not work, legion toolkit does not work

Apologies for the redundancy but I need to check, neither of these *detect* or *change* the keyboard lights in their respective menus? Or do they only not *change* them?

If you are still under warranty, just hit Lenovo up and have them fix it. You might also want to search around device manager and see if you can reset/search for drivers for whatever keyboard interface there is.

**Comment by CactusRaven** [comment]
Vantage neither detects nor changes lights, Toolkit detects but cannot change. And, everything I've seen in device manager says its up to date.

**Comment by 4JX** [comment]
Yeah then it doesn't look like I can do much about it, probably a deeper issue than "vantage is jank" related to the keyboard's firmware or hardware.
