### ISSUE TITLE
Startup in Tray (Windows)

### ISSUE THREAD

**Issue by Paslik19** [4JX/L5P-Keyboard-RGB#153]
Tell me, please, how to make the program start automatically in the tray? I warn you right away that my level of knowledge and skills could be better. I tried to do it through Task Scheduler but it didn't work. I managed to run it hidden (displayed only in the task manager), but in addition, for some reason, the program settings were not loaded. I tried to play with the arguments -tray and -minimized (I don't know if it works like that) and I tried to add the settings file to the startup.

**Comment by 4JX** [comment]
> I tried to do it through Task Scheduler but it didn't work. I managed to run it hidden (displayed only in the task manager), but in addition, for some reason, the program settings were not loaded.

You mean that if run from the task scheduler it wont load your config? That may be because its setting the directory the app is executed on to somewhere else. Can you provide screenshots?

> I tried to play with the arguments -tray and -minimized (I don't know if it works like that)

The correct flags are `--gui` (start the UI) and `--hideWindow` (but keep it minimized)

> and I tried to add the settings file to the startup.

Again, screenshots please

**Comment by Paslik19** [comment]
Thanks for the answer! Unfortunately, after I recreated the task with the arguments you specified, nothing worked for me. Also, I want to warn that this is my first real attempt to make a task in the Task Scheduler, as it did not happen. Could you take a look at the screenshots to see exactly what I'm doing wrong

<details>
 <summary> Screenshots: </summary>

![image](https://github.com/4JX/L5P-Keyboard-RGB/assets/107281151/a0d3db08-a3f5-4550-a5a1-c1198d1889f0)
![image](https://github.com/4JX/L5P-Keyboard-RGB/assets/107281151/bc5baa47-3aae-434b-a749-7fa20ee45722)
![image](https://github.com/4JX/L5P-Keyboard-RGB/assets/107281151/88ff808a-3ce9-4d84-91f9-8aa2c70b48c8)
![image](https://github.com/4JX/L5P-Keyboard-RGB/assets/107281151/bd2efa93-0a75-4abb-9602-cbf78a1d1e08)
![image](https://github.com/4JX/L5P-Keyboard-RGB/assets/107281151/e9cfde0b-63a9-4111-8586-7c74cca4dffc)
![image](https://github.com/4JX/L5P-Keyboard-RGB/assets/107281151/4548f0a9-a289-4d3a-b11b-4e963d943f74)
![image](https://github.com/4JX/L5P-Keyboard-RGB/assets/107281151/ba67edf2-9431-44a3-809a-45722adac865)
![image](https://github.com/4JX/L5P-Keyboard-RGB/assets/107281151/2dfeddab-38b7-441d-9f0b-b27b4058d104)

</detalis>

**Comment by Paslik19** [comment]
Thanks for the answer! Unfortunately, after I recreated the task with the arguments you specified, nothing worked for me. Also, I want to warn that this is my first real attempt to make a task in the Task Scheduler, as it did not happen. Could you take a look at the screenshots to see exactly what I'm doing wrong

<details>
 <summary> Screenshots: </summary>

![image](https://github.com/4JX/L5P-Keyboard-RGB/assets/107281151/a0d3db08-a3f5-4550-a5a1-c1198d1889f0)
![image](https://github.com/4JX/L5P-Keyboard-RGB/assets/107281151/bc5baa47-3aae-434b-a749-7fa20ee45722)
![image](https://github.com/4JX/L5P-Keyboard-RGB/assets/107281151/88ff808a-3ce9-4d84-91f9-8aa2c70b48c8)
![image](https://github.com/4JX/L5P-Keyboard-RGB/assets/107281151/bd2efa93-0a75-4abb-9602-cbf78a1d1e08)
![image](https://github.com/4JX/L5P-Keyboard-RGB/assets/107281151/e9cfde0b-63a9-4111-8586-7c74cca4dffc)
![image](https://github.com/4JX/L5P-Keyboard-RGB/assets/107281151/4548f0a9-a289-4d3a-b11b-4e963d943f74)
![image](https://github.com/4JX/L5P-Keyboard-RGB/assets/107281151/ba67edf2-9431-44a3-809a-45722adac865)
![image](https://github.com/4JX/L5P-Keyboard-RGB/assets/107281151/2dfeddab-38b7-441d-9f0b-b27b4058d104)

</detalis>

**Comment by 4JX** [comment]
Only thing I can imagine is "run with highest privileges" is somehow messing with this. Another user reported having luck configuring it through LenovoLegionToolkit https://github.com/4JX/L5P-Keyboard-RGB/discussions/111#discussioncomment-9330594

**Comment by Paslik19** [comment]
Thank you for your response. It did work as expected. Also, I think it was still possible to get it to work adequately with standard Windows tools, but it's so crooked...
