### ISSUE TITLE
Startup in linux

### ISSUE THREAD

**Issue by nerounci** [4JX/L5P-Keyboard-RGB#154]
Hey! Im linux newbie and i wondering is there any way to add your program to linux startup so thats presets are saved and keyboard backlight are works upon the system boot?
Im using Legion 5 15LTH6
Os: Arch linux with gnome

**Comment by 4JX** [comment]
There's different ways to go about it and I do not have experience with Arch. The Arch wiki has [quite a few methods](https://wiki.archlinux.org/title/Autostarting).
