### ISSUE TITLE
Not supported on Legion 5i 2024 (16IRX9 )

### ISSUE THREAD

**Issue by j-biswas** [4JX/L5P-Keyboard-RGB#155]
"Failed to find a valid keyboard."
<img width="377" alt="Screenshot 2024-05-04 002445" src="https://github.com/4JX/L5P-Keyboard-RGB/assets/79597886/1dd85cdb-c3f8-4510-8044-dca98cc1f8d1">

**Comment by 4JX** [comment]
Doing a sanity check,  do have an RGB keyboard? Is it detected in vantage and can you change it over there?

**Comment by j-biswas** [comment]
> Doing a sanity check, do have an RGB keyboard? Is it detected in vantage and can you change it over there?

Yes, i have 4 zone rgb keyboard and it can be detected by vantage but lenovo Spectrum is little bit glitchy so I use lenovo legion toolkit to control the rgb (which works fine but I heard yours is better)

**Comment by 4JX** [comment]
Can you screenshot what https://github.com/4JX/L5P-Keyboard-RGB/actions/runs/9007728363 outputs? (When it finishes building)

**Comment by 4JX** [comment]
Oh, good catch, my bad. Looks like Lenovo started separating the base and pro keyboard IDs as they do with the budget ideapad/LOQ models. I always found it strange that I ended up with 3 IDs for the 2023 models.

Hopefully this one does the trick: https://github.com/4JX/L5P-Keyboard-RGB/actions/runs/9009219636

**Comment by j-biswas** [comment]
yep it is working now....thank you so much .
