### ISSUE TITLE
Not supported on Legion Slim 7 16APH8 

### ISSUE THREAD

**Issue by Prn-Ice** [4JX/L5P-Keyboard-RGB#156]
The docs did not mention the legion 7 so I expected it would not work.
I have some programming experience, do you think I can update this package so it works with my computer?

**Comment by 4JX** [comment]
The 7 series works rather differently to the 5 and AFAIK (at least used to) uses the corsair protocol. A better place to look for inspiration for this would probably be OpenRGB.

The internals of this program are not "generalized" enough to easily adapt to also supporting legion 7's and it's not something I personally need/want to add, but there's always a chance it could work out.
