### ISSUE TITLE
Not detected on Arch

### ISSUE THREAD

**Issue by ms4rkl** [4JX/L5P-Keyboard-RGB#159]
Error: Couldn't find device (ar app(src(effects/mod.rs:89:14)    after running precompiled version on Arch. (Lenovo Legion 5 Pro 16ACH6H)

**Comment by 4JX** [comment]
Need to either run it with sudo or https://github.com/4JX/L5P-Keyboard-RGB?tab=readme-ov-file#usage

**Comment by michal-markl** [comment]
![Screenshot from 2024-05-29 16-40-37](https://github.com/4JX/L5P-Keyboard-RGB/assets/93058524/d6b9323f-2dd3-4ac4-90b0-4dc655aa1b6e)

**Comment by 4JX** [comment]
Do you have a white backlight or RGB keyboard?

https://github.com/4JX/L5P-Keyboard-RGB?tab=readme-ov-file#how-about-x-model

**Comment by 4JX** [comment]
If you have it installed, does vantage on windows detect your device? Can you control the lights manually? What about `lsusb` on linux?

![image](https://github.com/4JX/L5P-Keyboard-RGB/assets/79868816/42bf72ff-50c8-42d0-bfcb-6f7f8e34472e)

**Comment by michal-markl** [comment]
It used to work on Windows, but currently I am only able to use the preset (factory) modes for the lighting on Windows and Linux too.

![image](https://github.com/4JX/L5P-Keyboard-RGB/assets/93058524/8f8c61f3-7e70-4771-9434-3587069754c7)

**Comment by 4JX** [comment]
> It used to work on Windows, but currently I am only able to use the preset (factory) modes for the lighting on Windows and Linux too.

There's been more than a few accounts of the rgb controller bits of the keyboard being broken, at least that I can recall. Some were able to solve their issue by using this program, but this looks like a deeper/worse issue. 

There's still a chance it could be software related, maybe try something like a live image of some other distro?

**Comment by ms4rkl** [comment]
I've already tried that in Ubuntu. No change.

**Comment by 4JX** [comment]
Then I can only suspect either firmware level bugs or hardware damage of some sort. Not much I can do at that point, at least as far as I know.
