### ISSUE TITLE
Legion 5 Pro 16IAH7H (Support request)

### ISSUE THREAD

**Issue by ThunderRuler** [4JX/L5P-Keyboard-RGB#164]
Here's the list as provided by the ![Screenshot 2024-07-10 051931](https://github.com/4JX/L5P-Keyboard-RGB/assets/30215349/bc229035-9561-4dbb-88f6-8db6186ea0a7):

0x046d:0xc54d
0x04f3:0x31ad
0x043e:0x9a8a
0x04f3:0x31ad
0x043e:0x9a8a
0x048d:0xc102
0x0bda:0x4027
0x046d:0xc54d
0x0bda:0x4027
0x048d:0xc102
0x046d:0xc54d
0x048d:0xc102

I'm just creating a request to have this laptop supported :)

**Comment by 4JX** [comment]
This being a 2022 model it should already be supported by the app. I'm however not seeing the [expected](https://github.com/4JX/L5P-Keyboard-RGB/blob/7b19a1fdd4e842947bf777bb1049ab26ca4e2d8c/driver/src/lib.rs#L21) ID for that model on the list.

Do you have a 4 zone RGB keyboard or a white/blue backlight one?

**Comment by ThunderRuler** [comment]
> This being a 2022 model it should already be supported by the app. I'm however not seeing the [expected](https://github.com/4JX/L5P-Keyboard-RGB/blob/7b19a1fdd4e842947bf777bb1049ab26ca4e2d8c/driver/src/lib.rs#L21) ID for that model on the list.
> 
> Do you have a 4 zone RGB keyboard or a white/blue backlight one?

I have 4 zone RGB lighting.

**Comment by 4JX** [comment]
Does Vantage or any other program you use recognise the keyboard lights? If not then I can't do much about Lenovo's buggy firmware.

**Comment by ThunderRuler** [comment]
> Does Vantage or any other program you use recognise the keyboard lights? If not then I can't do much about Lenovo's buggy firmware.

Sometimes, which is why I was hoping that I could use your software. Half the time it doesn't display in Vantage and other times it will. No Windows update required either, it just comes back randomly and disappears just as random.

**Comment by 4JX** [comment]
There's various variants of the no detection issue, but if this program can't find it then it's most likely the keyboard itself that is faulty.
