### ISSUE TITLE
Lenovo Legion 5 Laptop 15ACH6 Type 82JW Failed to find a valid keyboard

### ISSUE THREAD

**Issue by Combopizza123** [4JX/L5P-Keyboard-RGB#165]
![image](https://github.com/user-attachments/assets/bf30d8ad-ed67-4ff4-9511-b8db98b55d12)

![image](https://github.com/user-attachments/assets/df49e632-e81a-4ede-ab3c-e22b761c1dcd)

I was able to use this software to turn off RGB back then but now it doesn't work. 

FN+Spacebar wasn't turning off the RGB on the keyboard and Lenovo Legion toolkit says that RGB is off on the keyboard but the light is still on.

The keyboard has RGB lights, 4 zone RGB keyboard

**Comment by 4JX** [comment]
Oddly enough just had that happen with mine on Linux. After that I:

- (Suspecting something malicious from Lenovo) Changed my BIOS date back a bit
- Rebooted into windows
- Had to change the date back to normal
- Installed LenovoLegionToolkit for testing and terminated all Lenovo Vantage processes
- Proceeded to have a working keyboard again in both Toolkit and this one

**Comment by Combopizza123** [comment]
Hi, thanks for responding
I tried setting the BIOS date back a bit, saved the changes and exit from BIOS. 
The time didn't change once I reboot back into windows
RGB on the keyboard is still on and FN+space doesn't work still to turn off RGB but the square notification on screen shows up to indicate the modes changing.

LenovoLegionToolkit still doesn't turn off RGB either.

Not sure what to do now.

**Comment by 4JX** [comment]
Would try installing drivers from Lenovo's page or contacting Lenovo support at that point, nothing much I can do here.
