### ISSUE TITLE
Legion Pro 7i (16IRX9H) Compatibility Request

### ISSUE THREAD

**Issue by judgementcole** [4JX/L5P-Keyboard-RGB#166]
The keyboard works fine with Vantage. I just really don't like the presets and the lack of customizability. So I would like to try out the presets and/or program my own, using this app.

![OpenRGB Errors](https://github.com/user-attachments/assets/3b7141f0-4ca2-4e36-96d2-d5b2b737d566)

**Comment by 4JX** [comment]
Legion 7 models aren't and wont be supported as I do not own one for development/testing. Consider [OpenRGB](https://openrgb.org/) or [LenovoLegionToolkit](https://github.com/BartoszCichecki/LenovoLegionToolkit)
