### ISSUE TITLE
UDEV rules for 2024 models

### ISSUE THREAD

**Issue by LukasJerabek** [4JX/L5P-Keyboard-RGB#179]
I have 2024 model and udev rules for 2023 doesnt work for me, where do I find what needs to be done? How can I help so that you guys could update the documentation? Thank you for your project!

Ubuntu 24.04

**Comment by 4JX** [comment]
Added the 2024 ones, check that it works
https://github.com/4JX/L5P-Keyboard-RGB?tab=readme-ov-file#usage

**Comment by LukasJerabek** [comment]
I have checked only regular, since thats the one I have. Works, great, thank you.
