### ISSUE TITLE
Error: Couldn't find device

### ISSUE THREAD

**Issue by MrLinuxOsu** [4JX/L5P-Keyboard-RGB#18]
Hey there. I have a Lenovo Legion 5 (not Pro) and I've tried running the executable and get this error:

`thread 'main' panicked at 'Error: Couldn't find device', src/main.rs:8:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by 4JX** [comment]
Is this a 2021 model *with* a 4 zone (not white backlight) keyboard?

**Comment by MrLinuxOsu** [comment]
I don't know about the age of this model, but I can confirm it is a 4 zone

**Comment by 4JX** [comment]
> I don't know about the age of this model, but I can confirm it is a 4 zone

What CPU does it have? What OS is the one you are testing in?

**Comment by 4JX** [comment]
Hey @Sak-667 and @MrLinuxOsu, there's a new release which enables support for the 2020 models, let me know how it goes.
https://github.com/4JX/L5P-Keyboard-RGB/releases/tag/v0.9.0

**Comment by Sak-667** [comment]
Hello, 
With sudo rights, it is all good with my keyboard now !

**Comment by 4JX** [comment]
Closing as solved
