### ISSUE TITLE
Application not starting on Legion 5 2020

### ISSUE THREAD

**Issue by 7FrostBites** [4JX/L5P-Keyboard-RGB#180]
![image](https://github.com/user-attachments/assets/b7a3141d-7331-4882-8d86-0efc46c8f020)
I tried to use this app since the lightning option isn't shown on lenovo vantage but the app didn't work

**Comment by 4JX** [comment]
You can try with LenovoLegionToolkit, but the more probable explanation is hardware/firmware being an issue. Solutions vary greatly between people so try searching the Lenovo help forums or the subreddit for information.
