### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by etobar** [4JX/L5P-Keyboard-RGB#22]
Windows security (on win 11) detects a trojan on v0.8.1

**Comment by 4JX** [comment]
I have no idea what causes it and its most likely out of my control. I'd assume it has to do with people seemingly "at random" (at least from the OS's perspective) suddenly having the same executable file downloaded somewhere. 

If you dont trust the binaries in the releases feel free to check the source code and build it yourself.

See:
https://github.com/4JX/L5P-Keyboard-RGB#building-from-source
Or an easier method, currently in the dev branch:
https://github.com/4JX/L5P-Keyboard-RGB/tree/dev#using-cargo-make

Sorry I can't give a proper explanation,.this has been an issue in previous releases too.
