### ISSUE TITLE
Legion 5 Pro after opening nothing

### ISSUE THREAD

**Issue by r0836332** [4JX/L5P-Keyboard-RGB#23]
Hello

Legion 5 Pro: 16ACH6H 4 zone RGB keyboard
Windows 11.

I wanted to open the program but literally nothing happens. (even in compability mode)
Trying to open the latest version and 0.7.0 do the same thing. 

I try to open it and maybe it instantly crashes but I see that nothing is happening.
It doesn't give any errors, just completely nothing.

Also installed Rust but it didn't help.

**Comment by 4JX** [comment]
Can you try running [v0.9.0](https://github.com/4JX/L5P-Keyboard-RGB/releases/tag/v0.9.0) with a console and sending the output? It'll hopefully contain more insight (aka a crash log) as other people seem to be able to run it just fine on W11.

**Comment by r0836332** [comment]
It just says: [process exited with code 101]

**Comment by 4JX** [comment]
Can you share the log in its entirety?

**Comment by r0836332** [comment]
> Can you share the log in its entirety?

Is it possible to tell me how to do this?
I have looked around for hours and I see program code that's used, but I am not a programmer and don't know how to apply it to the exe.

**Comment by 4JX** [comment]
@r0836332 When the "exited with 101" is printed to the console, does it output more text? If so, what's it?

**Comment by r0836332** [comment]
> @r0836332 When the "exited with 101" is printed to the console, does it output more text? If so, what's it?

That was literllay it. I opened it, then it showed that. Nothing else.

**Comment by 4JX** [comment]
Can you try [compiling it from source](https://github.com/4JX/L5P-Keyboard-RGB#building-from-source) yourself and seeing if that makes any difference? (An executable will be created in the path "target/debug/" or "target/release/" from the folder where you copied the project that you can test to see if it works).

If you have a discord account do you mind joining https://discord.gg/bJeCPM9q so I can assist you there?

**Comment by r0836332** [comment]
> Can you try [compiling it from source](https://github.com/4JX/L5P-Keyboard-RGB#building-from-source) yourself and seeing if that makes any difference? (An executable will be created in the path "target/debug/" or "target/release/" from the folder where you copied the project that you can test to see if it works).
> 
> If you have a discord account do you mind joining https://discord.gg/bJeCPM9q so I can assist you there?

Hello I am in the discord server, (Ghost Of Jaro#9308). I am experiencing issues trying to build it.

**Comment by 4JX** [comment]
Lenovo drivers bug - Outside of my reach for fixing (Solved on discord)

```
* For future readers please make sure the keyboard is already detected in Vantage. There's not much I can do if nothing on the software side of things can access the keyboard
```
