### ISSUE TITLE
Christmas theme

### ISSUE THREAD

**Issue by ItsVince1234** [4JX/L5P-Keyboard-RGB#28]
Can you create a christmas theme? Something that cycles between red and green maybe?

It would also be prettry cool if you can create your own effects

**Comment by 4JX** [comment]
> Can you create a christmas theme? Something that cycles between red and green maybe?
> 
> It would also be prettry cool if you can create your own effects

The latter is being worked on atm 😉. As for the earlier to make it more generic I could make it swap between the colors that have been entered into the zone fields (so if you had "red for the left, green for the center-left" as values it would go red>green>etc on the whole keyboard).

**Comment by ItsVince1234** [comment]
Ok, thank you! Great work!

**Comment by 4JX** [comment]
Ended up going for trying to emulate your good ol' Christmas tree lights instead. Let me know what you think about it.

**Comment by ItsVince1234** [comment]
This is fucking amazing dude! Great work!

**Comment by ItsVince1234** [comment]
I love the fading and switching zones!

**Comment by 4JX** [comment]
Closing as solved
