### ISSUE TITLE
Effects that don't use colors don't work in CLI

### ISSUE THREAD

**Issue by vpertys** [4JX/L5P-Keyboard-RGB#30]
OS: Windows 11

Effects such as AmbientLight, SmoothLeftWave, etc. give error `Invalid input, please check you used the correct format for the colors` when trying to use in CLI on v0.10.1. Used to work on v0.9.0

**Comment by 4JX** [comment]
Ah, seems like this commit broke it
https://github.com/4JX/L5P-Keyboard-RGB/commit/78c8caa2ee233f9c707925cc6f805ac90d7c14ad#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcL106

I'll issue a fix in a moment.

**Comment by 4JX** [comment]
I remember fixing this issue before, don't know why thr commit didn't go through. The binaries on v0.10.1 should now be the correct ones, apologies for the inconvenience. 

Let me know if it works for you now.

**Comment by vpertys** [comment]
It works now.
