### ISSUE TITLE
how to auto run

### ISSUE THREAD

**Issue by WhatsYourCookie** [4JX/L5P-Keyboard-RGB#33]
lights effects looks crazy,but how do i auto run the program with the last saved light settings

**Comment by 4JX** [comment]
I've held off adding this into the app until I can figure out if https://github.com/4JX/L5P-Keyboard-RGB/issues/26 is a one off issue or not.

(Assuming your'e on Windows) You can currently have it start automatically by either manually creating a task in the task scheduler or placing a shortcut to the app in the startup folder.

As for loading a specific profile when it starts, you'll need to either specify the effect and options through the command line mode or by placing a profile named `default.json` in the same folder the executable is in.

**Comment by WhatsYourCookie** [comment]
> I've held off adding this into the app until I can figure out if #26 is a one off issue or not.
> 
> (Assuming your'e on Windows) You can currently have it start automatically by either manually creating a task in the task scheduler or placing a shortcut to the app in the startup folder.
> 
> As for loading a specific profile when it starts, you'll need to either specify the effect and options through the command line mode or by placing a profile named `default.json` in the same folder the executable is in.

**Comment by WhatsYourCookie** [comment]
i dont know how to do command line can you please tell me how to auto load last saved light profile

**Comment by 4JX** [comment]
First, unzip the app and place it in a folder of your choosing. Open it, select the effect and settings you want and click "Profile" > "Save" and save the file as `default.json`.

![imagen](https://user-images.githubusercontent.com/79868816/143901827-d534dbbc-7f9d-4dbe-a715-4866cb0ff824.png)

It should be in the same folder as the app, like so:

![imagen](https://user-images.githubusercontent.com/79868816/143901939-6f21c62e-bda8-4c1f-8ab7-2dd432886744.png)

Hold the "Windows" key and R, a propmt will appear. Type `shell:startup` and hit Ok.

![imagen](https://user-images.githubusercontent.com/79868816/143902181-e126beb4-38ab-4543-8b71-d5008d4c5a4c.png)

You'll see a new window with a folder located at `C:\Users\YOUR_USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`. Make a shortcut of the app and place it there.

![imagen](https://user-images.githubusercontent.com/79868816/143902353-0df608f0-6fcc-4b21-8d9b-2a3674b14ec2.png)

Now whenever you reboot the app will automatically launch once you log in. If you want to change the effect that is used when the app launches simply save a new `default.json` profile. If you want to stop it from starting up again, delete the shorcut in the folder mentioned before.

I'll eventually add an option to launch without the window showing up, but for now this should work. Let me know how it goes.

**Comment by WhatsYourCookie** [comment]
thanks a lot it worked.Hope you will add 2 or more cool effects in future

**Comment by 4JX** [comment]
If anything comes to mind, do tell. Might be able to make it happen.

**Comment by WhatsYourCookie** [comment]
sure

**Comment by WhatsYourCookie** [comment]
> If anything comes to mind, do tell. Might be able to make it happen.

Can you please add some dynamic light mods similar to christmas? adding 2 or 3 new effects will be crazy im addicted to your software never uses lenovos light effects

**Comment by Kacas86** [comment]
Hi, thank you for this app. So many Legion 5 Pro with this problem. it's annoying that Lenovo cant handle.
I followed your instructions to add this to the startup. It worked, but it automatically popup on screen, so we have to close it to the tray everytime. Is it possible to start with windows but minimazed to the tray?

**Comment by 4JX** [comment]
@Kacas86 There is currently no way to start the app that way
