### ISSUE TITLE
App stopped working

### ISSUE THREAD

**Issue by Emjay32** [4JX/L5P-Keyboard-RGB#46]
I had the rainbow wave issue on my new Legion 5 Pro. But your app worked on the first try and I was able control the RGB lights. But just yesterday it stopped working. It work a few weeks in then it stopped. I would click on the legion-kb-rgb app but it did nothing. Clicked several times, but it's window would show ghost of it for a split second. Then I tried deleting it all and downloaded it again, with your latest update. It still did the same thing and kept clicking on it until a window popped up saying "Another instance of the program is already running, please close it before starting a new one" (see screenshot attached). Please note I know little about using command prompt but willing to try make this work.
![Screenshot (2)](https://user-images.githubusercontent.com/97222061/148360182-993bd64d-f0db-4776-add6-9a4967b98ca9.png)
.

**Comment by 4JX** [comment]
Does running [this build](https://github.com/4JX/L5P-Keyboard-RGB/suites/4797557881/artifacts/134464083) output anything different?

**Comment by Emjay32** [comment]
I tried it and this is what I got
![Screenshot (4)](https://user-images.githubusercontent.com/97222061/148528834-140177ba-91bd-4cbf-ae59-cce7a475b405.png)
.

**Comment by 4JX** [comment]
> I tried it and this is what I got ![Screenshot (4)](https://user-images.githubusercontent.com/97222061/148528834-140177ba-91bd-4cbf-ae59-cce7a475b405.png) .

Looks like you've encountered the same issue many others have ([related](https://github.com/4JX/L5P-Keyboard-RGB/issues/29) [issues](
