### ISSUE TITLE
Add keyboard

### ISSUE THREAD

**Issue by working-code** [4JX/L5P-Keyboard-RGB#47]
Hi.
Please add keyboard
`Bus 003 Device 011: ID 048d:c101 Integrated Technology Express, Inc. ITE Device(8910)`
[Lenovo Legion 5 Pro 16ITH6H 82JD000MRU](https://shop.lenovo.ru/product/82JD000MRU/)

print lsusb:

> Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 011: ID 048d:c101 Integrated Technology Express, Inc. ITE Device(8910)
Bus 003 Device 003: ID 09da:7e25 A4Tech Co., Ltd. USB Device 
Bus 003 Device 013: ID 8087:0026 Intel Corp. AX201 Bluetooth
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Thank you

**Comment by 4JX** [comment]
Hello, that device does not appear to be a valid "keyboard". Given you are using a Legion 5 Pro its most likely the correct device would be `048d:c965 Integrated Technology Express, Inc. ITE Device(8295)` which does not seem to appear on the list you provided.

This can indicate a hardware issue outside of my control. Are you able to control the lights on windows through Vantage?

**Comment by working-code** [comment]
When buying a laptop, it was installed windows 10.
Control the lights on windows through Vantage not work. error message "error driver"

now install arch linux.

**Comment by 4JX** [comment]
> Vantage not work. error message "error driver"

Then it's most likely a case of faulty hardware, not much I can do here.
