### ISSUE TITLE
Error returned - trying to open the GUI

### ISSUE THREAD

**Issue by nicholasyoannou** [4JX/L5P-Keyboard-RGB#48]
Double clicking on the file didn't work so I tried executing it in cmd and got some debug info. 

![image](https://user-images.githubusercontent.com/29736141/148839153-b435f7f1-768a-40b7-9065-b6aeac81b696.png)

**Comment by nicholasyoannou** [comment]
Device info - Legion 5 Gen 6 model

**Comment by MarkFifa** [comment]
I have the same issue. I just tried to run the .exe and nothing happened. Running as administrator or temporarily disabling my firewall both did not work. I am on windows 11. I will follow this topic. Same model.

**Comment by 4JX** [comment]
@nicholasyoannou Does your device present symptoms similar to https://github.com/4JX/L5P-Keyboard-RGB/issues/29?

Does executing [this](https://github.com/4JX/L5P-Keyboard-RGB/suites/4797557881/artifacts/134464083) output anything different?

**Comment by nicholasyoannou** [comment]
Weirdly enough in Vantage my in-built Lenovo keyboard can’t be detected. It’s been like this ever since I bought the laptop, I’m not sure if it’s required to install drivers or somewhat. I keep getting messages in the Vantage app saying ‘install drivers’ whenever I try the keyboard features, and attempting to check for updates, no keyboard driver updates were found. Unless I need to install iCue, I have no idea.

**Comment by 4JX** [comment]
> It’s been like this ever since I bought the laptop, I’m not sure if it’s required to install drivers or somewhat.

This app was initially born out of the (lack of) QA testing and batches of faulty keyboards/drivers/whatever causes it that Lenovo ships. You can try [a solution from reddit](https://www.reddit.com/r/LenovoLegion/comments/s0vpe8/rgb_keyboard_stuck_in_wave_mode_wont_turn_off/) to see if that does anything or just complain to Lenovo and send it in for fixing.

> Unless I need to install iCue, I have no idea.

That only works for the Legion 7 models.
