### ISSUE TITLE
Ambient and Temperature modes not Working on Linux

### ISSUE THREAD

**Issue by TheHawaiianKoala** [4JX/L5P-Keyboard-RGB#50]
Using Kubuntu with Kernel 5.13.0-25-generic and Plasma version 5.23.5, when using these two modes nothing happens. Kindly look into this issue. 

By the way, awesome app my dude

**Comment by 4JX** [comment]
Hey sorry for the late reply, I'm currently bussy irl so will try to replicate this issue in a bit.

What's your laptop's model? Are you using X11 or Wayland?

**Comment by TheHawaiianKoala** [comment]
Haha no worries, it a Lenovo Legion 5 Pro 16ith6h using X11

**Comment by 4JX** [comment]
Weird, the Ambient effect is working fine on a Live USB session (Non LTS). Temperature is indeed not working but that has probably more to do with the fact the CPU got support for reading temps in a newer kernel.

**Comment by TheHawaiianKoala** [comment]
Just tried ambient mode on a Live boot Kubuntu 21.10, it still doesnt work.

**Comment by 4JX** [comment]
Could you try the live version of something like EndeavourOS/Arch to see if a more up to date kernel and dependencies make any difference? Otherwise I'm sorry but I have no idea why Ambient would work on my machine but not yours.

**Comment by TheHawaiianKoala** [comment]
Can confirm it is working on a Live Boot of EndeavourOS. Seems I have to wait for Kubuntu to update some dependency
