### ISSUE TITLE
My RGB is stuck

### ISSUE THREAD

**Issue by am33mar** [4JX/L5P-Keyboard-RGB#52]
2 days ago I started using this software, it was great until today when the RGB animation suddenly stopped and I'm stuck with a static RGB that I cannot control.
I force-stopped the RGB app and tried to open it again but I got a message saying:
"A valid keyboard model was not found. It may be due to a hardware error."
when I open Lenovo vantage and try changing the RGB from there it says: 
"Driver Install Required .. install driver to activate lighting (Reboot Required)"
I tried restarting the pc but the RGB was stuck even in BIOS! and I couldn't turn it off or change it with Fn+Spacebar.
At last, I restored a system image which was 1 year old and which completely removed the old windows, but the same exact problem still exists!
here is the spec sheet:
https://psref.lenovo.com/Detail/Legion/Lenovo_Legion_5_15ARH05H?M=82B1005FAX
I hope that the problem can be solved and that the application didn't brick my RGB somehow, and thanks!

Edit: my last resort was to press the "NOVO button" with a paper clip, that button is like an "emergency" button used to boot up the laptop for the first time or if the boot failed, the RGB came back to normal and the problem is fixed!!!
I still dont know why this problem happened in the first place i will inform you if it happened again.

**Comment by 4JX** [comment]
There's so many issues with Lenovo's rgb on these machines that it's hard to tell when it was caused by my app, some other driver, an actual hardware problem or just the stars not aligning. Glad it worked out for you in the end though.
