### ISSUE TITLE
Lenovo Legion 7 Gen 6 AMD keyboard not recognized

### ISSUE THREAD

**Issue by somestupidfuck** [4JX/L5P-Keyboard-RGB#54]
Lenovo Legion 7 Gen 6 AMD
model 16ACHg6 
part number 82N6007RUS 
Windows 10 Home 20H2 (build 19042.1526)

Running the executable (or as admin) returns error "A valid keyboard model was not found. It may be due to a hardware error."

**Comment by 4JX** [comment]
Legion 7s are not supported by this program, see also https://github.com/4JX/L5P-Keyboard-RGB#compatibility.
