### ISSUE TITLE
Build process failing

### ISSUE THREAD

**Issue by matthew-henry** [4JX/L5P-Keyboard-RGB#55]
Hi,

I tried to build the project as described in the README, but ran into an issue as screenshoted below.  Not familiar with the Rust build process so it's entirely possible I've done this wrong.  I'm on Manjaro with Kernal 5.16.7-1

![image](https://user-images.githubusercontent.com/97588179/155699691-46f19d68-e81b-4c05-a5ca-90615f1563f2.png)

**Comment by matthew-henry** [comment]
Ok.  I actually got the build to proceed using the cargo make instructions in the github page.  Now I can't run the output file.  The file is marked executable in the permissions.  Running with sudo gets the same error message.

![image](https://user-images.githubusercontent.com/97588179/155719044-176b99b4-d441-459b-8a9a-79e3bdb262b2.png)

**Comment by 4JX** [comment]
As it is a file you need to run it relative to your current folder, so inside `/releases/` it'd be `./legion-kb-rgb`

**Comment by matthew-henry** [comment]
Ah, that was an embarrassing mistake, still a relative noobie on linux.  Thanks, everything looks to work fine.  Other than the seg fault when I forgot to sudo first.  Thanks for putting this together, not being able to control the keyboard lighting was a nuisance!
