### ISSUE TITLE
Suggestion: Start program while being minimized to system tray

### ISSUE THREAD

**Issue by Rodrxx** [4JX/L5P-Keyboard-RGB#56]
As shown in the title, a toggle which can start the application but by putting it on the system tray so it can be opened from there, ideal for startup when booting up the machine just not to make the setting console to stay there unless i click the red X or by minimizing it, it can make things cleaner

**Comment by 4JX** [comment]
Solved in [3a1706b](https://github.com/4JX/L5P-Keyboard-RGB/commit/3a1706babeaead1e791367da47c6d3953b2ae189), you can download the new version [here](https://github.com/4JX/L5P-Keyboard-RGB/releases/tag/v0.15.0)

**Comment by Kacas86** [comment]
Hi. I downloaded the new version for windows but cant make it start minimized. is it only for linux?

**Comment by 4JX** [comment]
> Hi. I downloaded the new version for windows but cant make it start minimized. is it only for linux?

To start it minimized you need to run it from the command line with the `HiddenWindow` argument, so `./l5p-kb-rgb.exe HiddenWindow`.

**Comment by Kacas86** [comment]
Sorry I'm a begginer. How I run a command line on startup?

**Comment by Rodrxx** [comment]
> Sorry I'm a begginer. How I run a command line on startup?

Im in the same train, what i did by the moment is right click on the shortcut present on the startup folder and then properties, and somewhere just change from normal to minimize

**Comment by Kacas86** [comment]
> > Sorry I'm a begginer. How I run a command line on startup?
> 
> Im in the same train, what i did by the moment is right click on the shortcut present on the startup folder and then properties, and somewhere just change from normal to minimize

thank you! that worked like a charm
