### ISSUE TITLE
Won't run on Archcraft Linux

### ISSUE THREAD

**Issue by shadjo1** [4JX/L5P-Keyboard-RGB#66]
**Problem**
Every time I try to run this as a non-root userI get the following error:

floating point exception (core dumped)

I have added the needed udev rule and reloaded the rules, so I'm not sure why it won't launch. However, it does work when I run it as root. Although that gives me this error:

pango_font_description_set_absolute_size: assertion 'desc != NULL' failed

**Notes**
I checked to see if pango was installed, and version 1.50.7.1 is present

I didn't build from source, instead I used the zip archive

I'm not sure what to do at this point besides trying to build from source and seeing if that works. Any other suggestions?

**Comment by 4JX** [comment]
Does the CLI interface work?

**Comment by 4JX** [comment]
This is really weird, can you try compiling it from source?

**Comment by shadjo1** [comment]
I tried that before and got the same result. But that was before I fixed the udev typo. When I get the chance I'll test it out and give an update.

**Comment by 4JX** [comment]
Closed due to inactivity
