### ISSUE TITLE
Support for Lenovo Ideapad Gaming 3 15ACH6

### ISSUE THREAD

**Issue by black3539** [4JX/L5P-Keyboard-RGB#67]
Any support coming from this model. FYI it has the same keyboard as the Legion's so i don't think it would make a difference

**Comment by 4JX** [comment]
Please record and attach an usbpcap capture log done with wireshark while you change the color settings with vantage.

**Comment by black3539** [comment]
[rgb.csv](https://github.com/4JX/L5P-Keyboard-RGB/files/8882260/rgb.csv)
Is this what you want or in another format?

**Comment by 4JX** [comment]
Use the `.pcapng` format instead

**Comment by black3539** [comment]
https://drive.google.com/file/d/1zYxQVSjdzzrj0FqrPg95h1SWbUPtVAO8/view?usp=sharing
this will also be more clear since i removed my usb mouse that i had

**Comment by 4JX** [comment]
Please download and run [kb-test.zip](https://github.com/4JX/L5P-Keyboard-RGB/files/8884089/kb-test.zip) from the console and provide the output

**Comment by black3539** [comment]
![Scr cap](https://user-images.githubusercontent.com/20815653/173192324-0b6efa60-4878-4367-977b-00d4f6fee8ef.png)
This is what i managed to capture, when it said good my kb turned off

**Comment by 4JX** [comment]
Try to execute this one: [legion-kb-rgb.zip](https://github.com/4JX/L5P-Keyboard-RGB/files/8884294/legion-kb-rgb.zip)

**Comment by black3539** [comment]
Yes, its working i think almost perfectly now. GG's my guy, how did you manage to do so much better work than lenovo, lol?
Very nice, i will follow your project closely man, you have a bright future

**Comment by 4JX** [comment]
> how did you manage to do so much better work than lenovo, lol?

By not being a greedy corporation that wants to reserve the true flashy lights for their higher end laptops 😛

**Comment by GizmoTheGreen** [comment]
Hi, I have this model, IdeaPad Gaming 3. with AMD Ryzen 5600H and RTX 3050.
it appears it's not compatible, because my specific variant of this model laptop only has White backlight (1 big zone), I see no options for RGB or any keyboard backlight control in Lenovo Vantage.

just an fyi might wanna add to the release info only specific variants of this model...

**Comment by 4JX** [comment]
It is noted in the readme https://github.com/4JX/L5P-Keyboard-RGB#compatibility

**Comment by GizmoTheGreen** [comment]
ah, I should have checked all the documentation I guess.
as you say in that doc the only states are off, medium and full on.
it's possible it's not connected in such a way to communicate with it but it's on standalone circuit.

the only thing I can think of to do with it -if- you can talk to it, is maybe strobe to music.

anyway, thanks for the reply and best of luck with the project, keep up the good work! :)
