### ISSUE TITLE
Question about Fn+Space handling

### ISSUE THREAD

**Issue by BartoszCichecki** [4JX/L5P-Keyboard-RGB#70]
Hey,

I the author of https://github.com/BartoszCichecki/LenovoLegionToolkit and I am in progress of adding RGB support.

The problem I see is that I listen to WMI even `LENOVO_GAMEZONE_LIGHT_PROFILE_CHANGE_EVENT` to detect Fn+Space presses. However it seem like the keyboard still attempts to switch the internal profile, so there is a little bit of flickering.

Vantage somehow manages to disable the internal profiles and I cannot figure out how.

Did you encounter similar issue?

**Comment by 4JX** [comment]
I originally wanted to use Fn+Space as well but I got annoyed enough at trying to make it behave that I just skipped over the problem altogether and used a different keybind.

**Comment by AtlasXT9** [comment]
@4JX  what is the keybind that you've added? im unable to remember
