### ISSUE TITLE
AmbientLight effect sensitivity/speed adjustment parameter

### ISSUE THREAD

**Issue by ccelik97** [4JX/L5P-Keyboard-RGB#71]
Hi. Props to you for putting this program together, it works fine on my Legion 5 (15ARH05H).

It's working fine overall but, at times the program is reportedly using 8%+ CPU including while not much/anything is going on the screen.

So, to minimize the load on the CPU I think it's be nice to have a parameter to set the rate of the screen reading so that we can have it respond quick enough to our preferences while also saving some system resources. I know, these are beasty machines and all but for one I'd be fine with even half the detection rate/reaction time knowing that the program isn't doing that at times 8%+ processing anymore. :D

**Comment by 4JX** [comment]
Yeah the screen capture code could do with some tuning, I'll see about showing an FPS option while the effect is active. (Or just tying the poll rate to the speed one, but that's probably too unintuitive).

**Comment by ccelik97** [comment]
A FPS parameter would be nice and you could also make the color ranges a bit wider (for example cut down the brightest ranges, leave the dimmer/less saturated ones) so that it wouldn't look choppy at lower FPS/sensitivity rates. As in just throwing some more ideas in in case something clicks with you. :D

**Comment by 4JX** [comment]
Implemented in v0.18.0
