### ISSUE TITLE
App runs only from terminal with sudo privilege

### ISSUE THREAD

**Issue by andreivoinescu** [4JX/L5P-Keyboard-RGB#73]
I tried using Alacarte to add the program to the app list, but it doesn't run even with run in terminal enabled
The program is located in /usr/bin and double clicking it doesn't work

![Screenshot from 2022-08-12 01-49-10](https://user-images.githubusercontent.com/31478518/184255345-1added6b-0ddf-4ebd-ba94-52a0c6ad36aa.png)
![Screenshot from 2022-08-12 01-56-36](https://user-images.githubusercontent.com/31478518/184256199-d638a109-72e1-451d-841e-097cccd09dd0.png)

**Comment by 4JX** [comment]
That floating point error message leads me to believe its something to do with library compilation shenanigans.

Can you try to compile it yourself? There's information on the readme on how to do so.

**Comment by 4JX** [comment]
Closed due to inactivity
