### ISSUE TITLE
Asking For launch 

### ISSUE THREAD

**Issue by rafay99-epic** [4JX/L5P-Keyboard-RGB#77]
## Question? 
The application is compiled and it's a success.. The main Question is how to run the application for the first time.?

## System Info:
My current device is Lenovo Legion 7 Slim.
Specification are: 
 - 16GB Ram
 - 512 SSD
 - Pure Arch Linux
 - AMD Ryzen 7 5800H
 - Nvidia RTX 3060

**Comment by 4JX** [comment]
If I recall correctly the slim 7 shares the full rgb KB with the normal 7, thus this program won't work there.

**Comment by rafay99-epic** [comment]
Great...Okay thanks for the Info..Do you have any recommendation how can get my keyboard RGB Working.

**Comment by rafay99-epic** [comment]
Okay...Thank you so much.
