### ISSUE TITLE
How to create presets/ CLI issue

### ISSUE THREAD

**Issue by 650on99** [4JX/L5P-Keyboard-RGB#78]
1. I know this could be sound stupid but how do you create presets? I cant see it anywhere in this repo. Can anyone point it out for me if i was just being blind. 
2. the cli doesnt read ripple as a valid effect parameter

**Comment by 4JX** [comment]
1. Click on the presets tab, input any combination of colors + effect + options and tap the + sign.

2. Ah I forgot to add it, I should untangle the codebase a bit sometime to automate this

**Comment by 650on99** [comment]
1. thx, I think the color of the + and - button are too dark, I can barely see it even after you told me there is a + sign
2. presets with ripple doesn't work properly, it loads in the colors but the effect becomes static when trying to load the preset

this program is so much better than lenovo's bs, keep it up <3
