### ISSUE TITLE
Trouble building on Linux

### ISSUE THREAD

**Issue by agronick** [4JX/L5P-Keyboard-RGB#79]
I had a trouble running the app on linux and it gave me 

```
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: DeviceNotFound
Location: src/cli.rs:74
```
DeviceNotFound gets thrown from here

```rs
 api
		.device_list()
		.find(|d| {
			let info_tuple = (d.vendor_id(), d.product_id(), d.usage_page(), d.usage());
			info_tuple == DEVICE_INFO_2021 || info_tuple == DEVICE_INFO_2020 || info_tuple == DEVICE_INFO_IDEAPAD_2021
		})
		.ok_or(error::Error::DeviceNotFound)?;
```

I was trying to compile the code to see why it couldn't recognize my device. After installing a ton of dependencies it succeeds to build but fails to run a custom build command `failed to run custom build command for scrap v0.5.0 (/home/kyle/Apps/projects/L5P-Keyboard-RGB/libs/scrap)`.

That `scrap` script is saying `Failed to find package: VcpkgNotFound("No vcpkg installation found. Set the VCPKG_ROOT environment variable or run 'vcpkg integrate install'")', libs/scrap/build.rs:7:45`. `

vcpkg is apparently a Windows thing so how can I get this work on Linux?

**Comment by 4JX** [comment]
https://github.com/Microsoft/vcpkg#getting-started
