### ISSUE TITLE
Can only modify one out of four presets

### ISSUE THREAD

**Issue by luisschwab** [4JX/L5P-Keyboard-RGB#82]
When running linux and using this tool, I can only modify one preset, the other 3 remain as default: pulse, wave and fade. On windows, upon setting it with the proprietary Lenovo software, it loads them up upon booting.

Is this limitation caused by proprietary firmware level stuff, reverse engineering difficulties, or what?
Would definitely like to help on this matter as it is kinda annoying having some RGB on your face while I switch to my preset at 3 in the morning.

**Comment by 4JX** [comment]
The program makes no attempt at configuring specific preset slots. It just sets the colors as needed directly. It's simply not something I've dived into implementing

**Comment by luisschwab** [comment]
Cool, i'll look into it
