### ISSUE TITLE
Support for Lenovo Legion 5 15IAH7H

### ISSUE THREAD

**Issue by rycerzes** [4JX/L5P-Keyboard-RGB#85]
Hello there,

I recently got a Legion 5 15IAH7H and would like to add support for my keyboard. Is there any information that is required?
 ![image](https://user-images.githubusercontent.com/59965507/193409743-17f761f1-414b-4653-aa09-776763eb2a86.png)

**Comment by 4JX** [comment]
I assume this is a 2022 model? If so, can you try running the version from [here](https://github.com/4JX/L5P-Keyboard-RGB/actions/runs/3100274787)?
