### ISSUE TITLE
PLEASE COME NEW EFFECTS

### ISSUE THREAD

**Issue by erenakdeniiiz** [4JX/L5P-Keyboard-RGB#95]
CONGRATULATIONS :))))
PLEASE COME NEW EFFECTS

**Comment by erenakdeniiiz** [comment]
if you do you will get a high donation thank you

**Comment by 4JX** [comment]
Anything in particular you want to have added?

**Comment by erenakdeniiiz** [comment]
NO ESPECIALLY BUT MORE EFFECTS COMING PLEASE

**Comment by erenakdeniiiz** [comment]
lütfen daha fazla efekt yap 3-4 adet farklı olsun
